{ pkgs, ... }:
{
  homebrew = {
    taps = [
      "homebrew/bundle"
      "homebrew/services"
      "deskflow/homebrew-tap"
      "tinted-theming/tinted"
    ];
    casks = [
      "betterdisplay"
      "deskflow"
      "iterm2"
      "macfuse"
      "utm"
      "vagrant"
      "vscodium"
      "pearcleaner"
    ];
    brews = [
      "act"
      # "automake"
      "awscli"
      "sqlite"
      "aria2"
      "bat"
      # "bison"
      "black"
      "bzip2"
      "cask"
      "chroma"
      "cmake"
      "curl"
      # "cython"
      "eza"
      "fd"
      "ffmpeg"
      # "flex"
      "fzf"
      "gcc"
      "gh"
      "git"
      "git-crypt"
      "git-lfs"
      "glab"
      "glow"
      "gnu-sed"
      "gnupg"
      "go"
      "gum"
      "pkg-config"
      "gobject-introspection"
      "gptfdisk"
      "ipython"
      "jq"
      "just"
      "ldid"
      "lf"
      "lftp"
      "libb2"
      "libffi"
      "libvirt"
      "lima"
      "llvm"
      "lzip"
      "lzo"
      "make"
      "mas"
      "meson"
      "micro"
      "most"
      "ncdu"
      # "node"
      "oci-cli"
      "openssl@3"
      "p7zip"
      # "paperkey"
      "perl"
      "pipenv"
      "pipx"
      # "pnpm"
      "podman"
      "pure"
      "pv"
      # "pygments"
      "qemu"
      # "qrencode"
      # "rbenv"
      "rclone"
      "ripgrep"
      "rsync"
      "rust"
      "rustup"
      "shc"
      "shellcheck"
      "tinty"
      "tree"
      "w3m"
      "wget"
      "yq"
      "zbar"
      "zlib"
    ];
  };
}
