{
  pkgs,
  inputs,
  ...
}: {
  xdg.configFile = {
    "micro/bindings.json".text = ''
      {
        "\u001b[1;2A": "SelectUp",
        "\u001b[1;2B": "SelectDown",
        "\u001b[1;2C": "SelectRight",
        "\u001b[1;2D": "SelectLeft",
        "\u001b[1;3D": "WordLeft",
        "\u001b[1;3C": "WordRight",
        "\u001b[1;3A": "MoveLinesUp",
        "\u001b[1;3B": "MoveLinesDown",
        "\u001b[1;4C": "SelectWordRight",
        "\u001b[1;4D": "SelectWordLeft",
        "\u001b[1;5D": "StartOfLine",
        "\u001b[1;5C": "EndOfLine",
        "\u001b[1;6D": "SelectToStartOfLine",
        "\u001b[1;6C": "SelectToEndOfLine",
        "\u001b[1;5A": "CursorStart",
        "\u001b[1;5B": "CursorEnd",
        "\u001b[1;6A": "SelectToStart",
        "\u001b[1;6B": "SelectToEnd",
        "Up":             "CursorUp",
        "Down":           "CursorDown",
        "Right":          "CursorRight",
        "Left":           "CursorLeft",
        "ShiftUp":        "SelectUp",
        "ShiftDown":      "SelectDown",
        "ShiftLeft":      "SelectLeft",
        "ShiftRight":     "SelectRight",
        "AltLeft":        "WordLeft",
        "AltRight":       "WordRight",
        "AltUp":          "MoveLinesUp",
        "AltDown":        "MoveLinesDown",
        "CtrlShiftRight": "SelectWordRight",
        "CtrlShiftLeft":  "SelectWordLeft",
        "AltLeft":        "StartOfTextToggle",
        "AltRight":       "EndOfLine",
        "AltShiftRight":  "SelectWordRight",
        "AltShiftLeft":   "SelectWordLeft",
        "CtrlLeft":       "StartOfText",
        "CtrlRight":      "EndOfLine",
        "AltShiftLeft":   "SelectToStartOfTextToggle",
        "CtrlShiftLeft":  "SelectToStartOfTextToggle",
        "ShiftHome":      "SelectToStartOfTextToggle",
        "AltShiftRight":  "SelectToEndOfLine",
        "CtrlShiftRight": "SelectToEndOfLine",
        "ShiftEnd":       "SelectToEndOfLine",
        "CtrlUp":         "CursorStart",
        "CtrlDown":       "CursorEnd",
        "CtrlShiftUp":    "SelectToStart",
        "CtrlShiftDown":  "SelectToEnd",
        "Alt-{":          "ParagraphPrevious",
        "Alt-}":          "ParagraphNext",
        "Enter":          "InsertNewline",
        "Ctrl-h":         "Backspace",
        "Backspace":      "Backspace",
        "Alt-CtrlH":      "DeleteWordLeft",
        "Alt-Backspace":  "DeleteWordLeft",
        "Tab":            "Autocomplete|IndentSelection|InsertTab",
        "Backtab":        "OutdentSelection|OutdentLine",
        "Ctrl-o":         "OpenFile",
        "Ctrl-s":         "Save",
        "Ctrl-f":         "Find",
        "Alt-F":          "FindLiteral",
        "Ctrl-n":         "FindNext",
        "Ctrl-p":         "FindPrevious",
        "Alt-[":          "DiffPrevious|CursorStart",
        "Alt-]":          "DiffNext|CursorEnd",
        "Ctrl-z":         "Undo",
        "Ctrl-y":         "Redo",
        "Ctrl-c":         "CopyLine|Copy",
        "Ctrl-x":         "Cut",
        "Ctrl-k":         "CutLine",
        "Ctrl-d":         "DuplicateLine",
        "Ctrl-v":         "Paste",
        "Ctrl-a":         "SelectAll",
        "Ctrl-t":         "AddTab",
        "Alt-,":          "PreviousTab",
        "Alt-.":          "NextTab",
        "Home":           "StartOfText",
        "End":            "EndOfLine",
        "CtrlHome":       "CursorStart",
        "CtrlEnd":        "CursorEnd",
        "PageUp":         "CursorPageUp",
        "PageDown":       "CursorPageDown",
        "CtrlPageUp":     "PreviousTab",
        "CtrlPageDown":   "NextTab",
        "Ctrl-g":         "ToggleHelp",
        "Alt-g":          "ToggleKeyMenu",
        "Ctrl-r":         "ToggleRuler",
        "Ctrl-l":         "command-edit:goto ",
        "Delete":         "Delete",
        "Ctrl-b":         "ShellMode",
        "Ctrl-q":         "Quit",
        "Ctrl-e":         "CommandMode",
        "Ctrl-w":         "NextSplit",
        "Ctrl-u":         "ToggleMacro",
        "Ctrl-j":         "PlayMacro",
        "Insert":         "ToggleOverwriteMode",

        // Mouse bindings
        "MouseWheelUp":   "ScrollUp",
        "MouseWheelDown": "ScrollDown",
        "MouseLeft":      "MousePress",
        "MouseMiddle":    "PastePrimary",
        "Ctrl-MouseLeft": "MouseMultiCursor"
      }
    '';

    "micro/settings.json".text = ''
      {
         "autoclose": true,
         "autoindent": true,
         "autosave": 0,
         "autosu": true,
         "backup": true,
         "backupdir": "",
         "basename": false,
         "clipboard": "external",
         "colorcolumn": 0,
         "colorscheme": "geany",
         "comment": true,
         "cursorline": true,
         "diff": true,
         "diffgutter": false,
         "divchars": "|-",
         "divreverse": true,
         "encoding": "utf-8",
         "eofnewline": true,
         "fastdirty": false,
         "fileformat": "unix",
         "filetype": "unknown",
         "incsearch": true,
         "ftoptions": true,
         "ignorecase": true,
         "indentchar": " ",
         "infobar": true,
         "initlua": true,
         "keepautoindent": false,
         "keymenu": false,
         "linter": true,
         "literate": true,
         "matchbrace": true,
         "mkparents": false,
         "mouse": true,
         "parsecursor": false,
         "paste": false,
         "permbackup": false,
         "pluginchannels": [
           "https://raw.githubusercontent.com/micro-editor/plugin-channel/master/channel.json"
         ],
         "pluginrepos": [],
         "readonly": false,
         "relativeruler": false,
         "reload": "auto",
         "rmtrailingws": true,
         "ruler": true,
         "savecursor": false,
         "savehistory": true,
         "saveundo": true,
         "scrollbar": false,
         "scrollmargin": 3,
         "scrollspeed": 2,
         "smartpaste": true,
         "softwrap": false,
         "splitbottom": true,
         "splitright": true,
         "status": true,
         "statusformatl": "$(filename) $(modified)($(line),$(col)) $(status.paste)| ft:$(opt:filetype) | $(opt:fileformat) | $(opt:encoding)",
         "statusformatr": "$(bind:ToggleKeyMenu): bindings, $(bind:ToggleHelp): help",
         "statusline": true,
         "sucmd": "sudo",
         "syntax": true,
         "tabmovement": false,
         "tabhighlight": true,
         "tabreverse": false,
         "tabsize": 2,
         "tabstospaces": true,
         "useprimary": true,
         "xterm": false,
         "autofmt.fmt-onsave": true
       }
    '';
  };
}
