---
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ github.token }}
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          extra-conf: |
            system = aarch64-linux
            experimental-features = nix-command flakes
            keep-outputs = true
            keep-derivations = true
      - run: sudo apt update && sudo apt install -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build -L --impure .#nixosConfigurations.nixos-macmini.config.system.build.toplevel

  build-darwin:
      runs-on: macos-latest
      permissions:
        contents: write
        id-token: write
      steps:
        - uses: actions/checkout@main
        - name: Unlock secrets
          uses: sliteteam/github-action-git-crypt-unlock@1.2.0
          env:
            GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        - uses: DeterminateSystems/nix-installer-action@main
          with:
            github-token: ${{ github.token }}
            source-url: https://install.lix.systems/lix/lix-installer-aarch64-darwin
            extra-conf: |
              system = aarch64-darwin
              experimental-features = nix-command flakes
              keep-outputs = true
              keep-derivations = true
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - run: nix build -L .#darwinConfigurations.macos.config.system.build.toplevel
