---
name: CI

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ github.token }}
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          extra-conf: |
            system = aarch64-linux
            experimental-features = nix-command flakes
            keep-outputs = true
            keep-derivations = true
      - name: git-crypt
        env:
          KEY_ENCODED: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          sudo apt update && sudo apt install git-crypt
          git config --global --add safe.directory "${PWD}"
          echo "${KEY_ENCODED}" | base64 -d | git-crypt unlock -
      - run: sudo apt install -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          sudo mount -o remount,size=15G /run/qemu
          sudo mount -o remount,size=15G /run/user/1001
          nix build -L --impure .#nixosConfigurations.nixos-macmini.config.system.build.toplevel

  build-darwin:
      runs-on: macos-latest
      permissions:
        contents: write
        id-token: write
      steps:
        - uses: actions/checkout@main
        - uses: DeterminateSystems/nix-installer-action@main
          with:
            github-token: ${{ github.token }}
            source-url: https://install.lix.systems/lix/lix-installer-aarch64-darwin
            extra-conf: |
              system = aarch64-darwin
              experimental-features = nix-command flakes
              keep-outputs = true
              keep-derivations = true
        - name: Set up Homebrew
          id: set-up-homebrew
          uses: Homebrew/actions/setup-homebrew@master
        - name: git-crypt
          env:
            KEY_ENCODED: ${{ secrets.GIT_CRYPT_KEY }}
          run: |
            brew install git-crypt
            git config --global --add safe.directory "${PWD}"
            echo "${KEY_ENCODED}" | base64 -d | git-crypt unlock -
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - run: nix build -L .#darwinConfigurations.macos.config.system.build.toplevel
