---
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: quinneden
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L --impure .#nixosConfigurations.nixos.config.system.build.toplevel